# General Writing Rule Configuration
# Comprehensive patterns for writing mistake detection with evidence-based scoring

writing_patterns:
  
  # === BASIC TEXT ISSUES ===
  
  repeated_words:
    pattern: "\\b(\\w+)\\s+\\1\\b"
    evidence: 0.9
    severity: "medium"
    message: "Repeated words detected"
    description: "Duplicate words are usually typing errors"
    
  extra_commas:
    pattern: ",\\s*,+"
    evidence: 0.9
    severity: "medium"
    message: "Extra commas detected"
    description: "Multiple consecutive commas are punctuation errors"
    
  missing_oxford_comma:
    pattern: "\\b\\w+,\\s+\\w+\\s+and\\s+\\w+\\b"
    evidence: 0.6
    severity: "low"
    message: "Consider adding Oxford comma"
    description: "Oxford comma usage depends on style guide preference"
    
  inconsistent_capitalization:
    pattern: "\\b([A-Z][a-z]+)\\s+([a-z][A-Z]+)"
    evidence: 0.7
    severity: "medium"
    message: "Inconsistent capitalization pattern"
    description: "Mixed capitalization within similar contexts"
    
  misplaced_apostrophe:
    pattern: "\\b\\w+'s\\s+\\w+|\\b\\w+s'\\s+\\w+"
    evidence: 0.6
    severity: "medium"
    message: "Check apostrophe placement"
    description: "Apostrophe usage should follow possessive rules"
  
  # === GRAMMAR ISSUES ===
  
  double_negative:
    pattern: "\\b(don't|doesn't|didn't|won't|can't|isn't|aren't|wasn't|weren't)\\s+(no|nothing|nobody|nowhere|never|neither)\\b"
    evidence: 0.8
    severity: "medium"
    message: "Double negative detected"
    description: "Double negatives can be confusing in formal writing"
    
  comma_splice:
    pattern: "\\b[a-zA-Z]+\\s*,\\s*[a-z][^.!?]*[.!?]"
    evidence: 0.6
    severity: "medium"
    message: "Possible comma splice"
    description: "Independent clauses should be separated properly"
  
  # === WORD USAGE ISSUES ===
  
  affect_effect:
    pattern: "\\b(affect|effect)\\b"
    evidence: 0.3  # Requires context analysis
    severity: "medium"
    message: "Check affect/effect usage"
    description: "Affect is usually a verb, effect is usually a noun"
    
  its_its:
    pattern: "\\b(its|it's)\\b"
    evidence: 0.3  # Requires context analysis
    severity: "medium"
    message: "Check its/it's usage"
    description: "Its is possessive, it's is a contraction for 'it is'"
    
  then_than:
    pattern: "\\b(then|than)\\b"
    evidence: 0.3  # Requires context analysis
    severity: "medium"
    message: "Check then/than usage"
    description: "Then indicates time/sequence, than indicates comparison"
    
  your_youre:
    pattern: "\\b(your|you're)\\b"
    evidence: 0.3  # Requires context analysis
    severity: "medium"
    message: "Check your/you're usage"
    description: "Your is possessive, you're is a contraction for 'you are'"
    
  there_their_theyre:
    pattern: "\\b(there|their|they're)\\b"
    evidence: 0.3  # Requires context analysis
    severity: "medium"
    message: "Check there/their/they're usage"
    description: "There is location/existence, their is possessive, they're is contraction"
  
  # === MISUSED CONTRACTIONS ===
  
  should_of:
    pattern: "\\bshould\\s+of\\b"
    evidence: 0.95
    severity: "high"
    message: "Use 'should have' instead of 'should of'"
    description: "Common error - should use 'should have' or 'should've'"
    
  could_of:
    pattern: "\\bcould\\s+of\\b"
    evidence: 0.95
    severity: "high"
    message: "Use 'could have' instead of 'could of'"
    description: "Common error - should use 'could have' or 'could've'"
    
  would_of:
    pattern: "\\bwould\\s+of\\b"
    evidence: 0.95
    severity: "high"
    message: "Use 'would have' instead of 'would of'"
    description: "Common error - should use 'would have' or 'would've'"
    
  might_of:
    pattern: "\\bmight\\s+of\\b"
    evidence: 0.95
    severity: "high"
    message: "Use 'might have' instead of 'might of'"
    description: "Common error - should use 'might have' or 'might've'"
  
  # === PREPOSITION ERRORS ===
  
  different_than:
    pattern: "\\bdifferent\\s+than\\b"
    evidence: 0.7
    severity: "low"
    message: "Consider 'different from' instead of 'different than'"
    description: "'Different from' is preferred in formal writing"
    
  try_and:
    pattern: "\\btry\\s+and\\b"
    evidence: 0.5
    severity: "low"
    message: "Consider 'try to' instead of 'try and'"
    description: "'Try to' is more precise than 'try and'"
  
  # === REDUNDANCY PATTERNS ===
  
  very_unique:
    pattern: "\\bvery\\s+unique\\b"
    evidence: 0.8
    severity: "medium"
    message: "Remove 'very' - unique means one of a kind"
    description: "Unique is an absolute term that doesn't need qualification"
    
  more_perfect:
    pattern: "\\bmore\\s+perfect\\b"
    evidence: 0.8
    severity: "medium"
    message: "Remove 'more' - perfect is absolute"
    description: "Perfect cannot be qualified with 'more'"
    
  most_unique:
    pattern: "\\bmost\\s+unique\\b"
    evidence: 0.8
    severity: "medium"
    message: "Remove 'most' - unique is absolute"
    description: "Unique cannot be compared with 'most'"
    
  very_essential:
    pattern: "\\bvery\\s+essential\\b"
    evidence: 0.7
    severity: "low"
    message: "Consider removing 'very' - essential is strong enough"
    description: "Essential already implies high importance"
  
  # === STYLE ISSUES ===
  
  passive_voice:
    pattern: "\\b(was|were|is|are|been|being)\\s+\\w+ed\\b"
    evidence: 0.4
    severity: "low"
    message: "Consider active voice instead of passive"
    description: "Active voice is often clearer and more direct"
    
  weak_verbs:
    pattern: "\\b(is|are|was|were|be|being|been)\\s+"
    evidence: 0.2
    severity: "low"
    message: "Consider stronger verbs"
    description: "Strong action verbs create more engaging writing"
  
  # === ADVANCED PUNCTUATION ===
  
  semicolon_misuse:
    pattern: ";[^A-Z\\s]"
    evidence: 0.7
    severity: "medium"
    message: "Check semicolon usage"
    description: "Semicolons should join independent clauses or separate complex lists"
    
  quote_inconsistency:
    pattern: '["\''].+?["\'']'
    evidence: 0.5
    severity: "low"
    message: "Check quote mark consistency"
    description: "Use consistent quote marks throughout document"

# === WORD CONFUSION ANALYSIS ===
# Detailed rules for commonly confused words

word_confusions:
  
  affect_effect:
    affect:
      typical_usage: "verb"
      contexts:
        correct_as_verb: ["influence", "change", "impact", "alter"]
        correct_as_noun: []  # Rare usage as noun (psychology term)
      examples:
        - "This will affect the outcome"
        - "The medication may affect your sleep"
      
    effect:
      typical_usage: "noun"  
      contexts:
        correct_as_noun: ["result", "consequence", "outcome", "impact"]
        correct_as_verb: ["cause", "bring about"]  # Less common
      examples:
        - "The effect was immediate"
        - "What was the effect of the change?"
        
  its_its:
    its:
      usage: "possessive_pronoun"
      contexts: ["ownership", "belonging", "characteristic"]
      examples:
        - "The dog wagged its tail"
        - "The company changed its policy"
        
    "it's":
      usage: "contraction"
      expands_to: ["it is", "it has"]
      test: "Can you replace with 'it is'?"
      examples:
        - "It's raining outside"
        - "It's been a long day"
        
  then_than:
    then:
      usage: "time_sequence"
      contexts: ["temporal", "sequence", "consequence"]
      examples:
        - "First this, then that"
        - "If you do this, then this happens"
        
    than:
      usage: "comparison"
      contexts: ["comparative", "preference", "degree"]
      examples:
        - "Better than before"
        - "More than expected"
        
  your_youre:
    your:
      usage: "possessive"
      contexts: ["ownership", "belonging"]
      examples:
        - "Your book is here"
        - "What's your opinion?"
        
    "you're":
      usage: "contraction"
      expands_to: "you are"
      test: "Can you replace with 'you are'?"
      examples:
        - "You're absolutely right"
        - "You're going to love this"

# === CONTEXT ANALYSIS RULES ===
# Rules for analyzing context to determine correct word usage

context_analysis:
  
  # Patterns that indicate specific usage
  affect_effect_contexts:
    affect_as_verb_indicators:
      - "will affect"
      - "may affect" 
      - "can affect"
      - "to affect"
      - "affecting"
      
    effect_as_noun_indicators:
      - "the effect"
      - "an effect"
      - "this effect"
      - "no effect"
      - "side effect"
      
    common_errors:
      - pattern: "\\b(the|an|this|that)\\s+affect\\b"
        should_be: "effect"
        evidence: 0.9
      - pattern: "\\b(will|would|can|could|may|might)\\s+effect\\b"
        should_be: "affect"
        evidence: 0.8
        
  its_contexts:
    possessive_indicators:
      - "its own"
      - "its color"
      - "its size" 
      - "its purpose"
      - "its function"
      
    contraction_errors:
      - pattern: "\\bits\\s+(time|working|ready|done|been)"
        should_be: "it's"
        evidence: 0.8

# === SENTENCE ANALYSIS SETTINGS ===
# Settings for analyzing sentence structure and complexity

sentence_analysis:
  
  # Length thresholds
  length_thresholds:
    run_on_sentence:
      word_count: 30        # 30+ words suggests run-on
      clause_count: 4       # 4+ clauses suggests complexity
      
    optimal_length:
      min_words: 8          # Very short sentences might be fragments
      max_words: 25         # Longer sentences harder to read
      
  # Complexity analysis
  complexity_indicators:
    coordination_conjunctions: ["and", "but", "or", "so", "yet"]
    subordination_conjunctions: ["because", "although", "while", "since", "if"]
    max_conjunctions: 3     # More than 3 suggests complexity
    
  # Fragment detection
  fragment_indicators:
    requires_main_verb: true
    requires_subject: true
    min_length: 3           # Sentences shorter than 3 words might be fragments
    
  # Tense consistency
  tense_analysis:
    check_consistency: true
    allow_intentional_shifts: true
    tense_shift_threshold: 0.3  # 30% different tense suggests inconsistency

# === EVIDENCE SCORING ADJUSTMENTS ===
# Fine-tune evidence based on various factors

evidence_adjustments:
  
  # Content type adjustments
  by_content_type:
    formal: 0.1             # More strict for formal writing
    technical: 0.05         # Slightly more strict for technical
    conversational: -0.1    # More permissive for conversational
    creative: -0.2          # Very permissive for creative writing
    academic: 0.15          # Most strict for academic writing
    
  # Context adjustments
  by_context:
    quotes: -0.8            # Very permissive in quotes (preserve original)
    dialogue: -0.6          # Permissive in dialogue
    code_comments: -0.3     # Slightly permissive in code comments
    headings: -0.2          # Slightly permissive in headings
    
  # Pattern-specific adjustments
  by_pattern:
    word_confusions:
      high_certainty_context: 0.3  # Boost when context is clear
      ambiguous_context: -0.2      # Reduce when context unclear
      
    redundancy:
      formal_writing: 0.2     # More strict in formal writing
      emphasis_context: -0.3  # Less strict when emphasis intended
      
    passive_voice:
      technical_writing: -0.2  # More acceptable in technical writing
      scientific_writing: -0.3 # Very acceptable in scientific writing
      
  # Frequency adjustments
  by_frequency:
    single_occurrence: 0.0   # No adjustment for single issues
    multiple_same_error: 0.2 # Boost evidence for repeated errors
    pattern_across_document: 0.3  # Strong evidence for document-wide patterns

# === SUGGESTION GENERATION ===
# Templates and logic for generating helpful suggestions

suggestion_templates:
  
  # Word confusion suggestions
  word_confusions:
    affect_effect:
      affect: 
        - "'Affect' is usually a verb meaning to influence"
        - "If you mean a result, use 'effect' (noun)"
        - "Remember: Affect = Action (verb), Effect = End result (noun)"
      effect:
        - "'Effect' is usually a noun meaning a result"
        - "If you mean to influence, use 'affect' (verb)"
        - "Remember: Affect = Action (verb), Effect = End result (noun)"
        
    its_contractions:
      its:
        - "'Its' shows possession (like his, her, their)"
        - "If you mean 'it is', use 'it's' (with apostrophe)"
        - "Possessive pronouns don't use apostrophes"
      "it's":
        - "'It's' is a contraction for 'it is' or 'it has'"
        - "If you mean possession, use 'its' (no apostrophe)"
        - "Test: Can you replace it with 'it is'? Then use 'it's'"
        
  # Grammar suggestions
  grammar_issues:
    double_negative:
      - "Use a single negative for clarity"
      - "Double negatives can be confusing in formal writing"
      - "Consider the intended meaning and use appropriate negation"
      
    subject_verb_disagreement:
      - "Check agreement between subject and verb"
      - "Singular subjects need singular verbs"
      - "Plural subjects need plural verbs"
      
    sentence_fragments:
      - "Add a main verb to complete the sentence"
      - "Ensure the sentence expresses a complete thought"
      - "Consider combining with another sentence"
      
  # Style suggestions
  style_improvements:
    passive_voice:
      - "Consider rewriting in active voice for clarity"
      - "Make the subject perform the action"
      - "Active voice is often more direct and engaging"
      
    wordy_phrases:
      - "Consider more concise phrasing"
      - "Eliminate unnecessary words"
      - "Use direct, clear language"
      
    run_on_sentences:
      - "Break this long sentence into shorter ones"
      - "Use periods to separate independent thoughts"
      - "Consider bullet points for complex information"

# === PERFORMANCE SETTINGS ===
performance:
  
  # Analysis limits
  max_sentences_analyzed: 200      # Reasonable limit for large documents
  max_word_confusions_checked: 50  # Limit context analysis calls
  
  # Pattern matching
  enable_regex_optimization: true
  cache_pattern_results: true
  parallel_pattern_matching: true
  
  # Context analysis
  context_window_size: 40         # Characters before/after for context
  enable_spacy_analysis: true     # Use spaCy when available
  fallback_analysis: true         # Always provide basic analysis
  
  # Skip conditions
  skip_very_short_sentences: true # Skip sentences < 3 words
  skip_single_word_errors: false  # Don't skip single word issues

# === QUALITY ASSURANCE ===
quality_assurance:
  
  # Validation thresholds
  minimum_evidence_threshold: 0.1
  high_confidence_threshold: 0.8
  require_context_validation: true
  
  # Error filtering
  filter_obvious_false_positives: true
  respect_domain_conventions: true
  consider_writing_style: true
  
  # Cross-validation
  validate_word_confusions: true  # Double-check word confusion context
  confirm_grammar_errors: true    # Verify grammar issues with multiple checks
  assess_style_appropriateness: true  # Consider if style suggestions fit context
