version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: content_editorial_assistant_db
    restart: always
    environment:
      - POSTGRES_USER=cea_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secure_change_me}
      - POSTGRES_DB=content_editorial_assistant
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    # Production PostgreSQL optimizations
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cea_user -d content_editorial_assistant"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local