:_newdoc-version: 2.18.5
:_template-generated: 2026-01-21
:_mod-docs-content-type: CONCEPT

[id="introduction-to-uki"]
= Introduction to Unified Kernel Image

[role="_abstract"]
To extend the secure boot protection throughout the entire boot chain, use Unified Kernel Image (UKI).

Components of UKI::

Unified Kernel Image (UKI) is a Unified Extensible Firmware Interface (UEFI) Portable Executable (PE) binary for the UEFI environment that bundles together the essential components of an operating system. UKI binary components extend the Secure Boot coverage by including the `initramfs` and the kernel command line. `Initramfs` is a part of the Linux startup process, while the kernel command line gives you limited access to define parameters. The primary components contained within the UKI binary are:

* The `.linux` section stores the Linux kernel image.
* The `.initrd` section stores the initial RAM filesystem `initramfs`.
* The `.cmdline` section stores the kernel command line.
* Additional sections, such as `.sbat`.
* The Red Hat signature.

Features of RHEL UKI with pre-built `initramfs`::

* Prohibits any malicious agent or component to alter any objects in the boot chain.
* Due to pre-built `initramfs`, the user does not need to build its custom `initramfs`, which results in a faster kernel installation.
* Provides support for the pre-built `initramfs` systems as it is similar in all installations such as virtual machine (VMs), containers, or cloud instances.
* Provides support for the `x86_64` architecture.
* Includes the `kernel-uki-virt` package.
* Built for virtual machines and cloud instances.

Limitation of UKI because of the reduced flexibility of the boot process::

* When building the UKI, the operating system vendor creates `initramfs`. As a consequence, the listed and included kernel modules are static. You can use the `systemd` system and configuration extensions to address this limitation.

* The kernel command line parameters are static, which limits the use of parameters for different instance sizes or debugging options.

You can use the UKI command line extensions to overcome this limitation.


