# Assembly Line Configuration - COMPLETE COVERAGE
# Automatically generates specialized instructions for ALL error types
# Based on comprehensive analysis of /rules directory

# Dynamic Assembly Line Processing - Block-Level Configuration
# Stations are created dynamically based on actual errors present in each block
processing_passes:
  urgent:
    name: "Critical/Legal Pass"
    display_name: "Critical/Legal Pass"
    description: "Legal compliance and critical content issues"
    priority_level: 1
    color: "red"
    icon: "fas fa-exclamation-triangle"
    categories: ["legal", "inclusive_language", "second_person", "claims"]
    error_types:
      - "legal_claims"
      - "legal_company_names" 
      - "legal_personal_information"
      - "inclusive_language"
      - "second_person"
  
  high:
    name: "Structural Pass"
    display_name: "Structural Pass"
    description: "Document structure and organization improvements"
    priority_level: 2
    color: "orange"
    icon: "fas fa-building"
    categories: ["passive_voice", "sentence_length", "subjunctive_mood", "verbs", "headings"]
    error_types:
      - "passive_voice"
      - "sentence_length"
      - "subjunctive_mood"
      - "verbs"
      - "headings"
  
  medium:
    name: "Grammar Pass"
    display_name: "Grammar Pass"
    description: "Grammar, word usage, and language improvements"
    priority_level: 3
    color: "gold"
    icon: "fas fa-spell-check"
    categories: ["word_usage", "anthropomorphism", "capitalization", "contractions", "prefixes", "plurals", "spelling", "terminology", "abbreviations"]
    error_types:
      - "word_usage_a"
      - "word_usage_b"
      - "word_usage_c"
      - "word_usage_d"
      - "word_usage_e"
      - "word_usage_f"
      - "word_usage_g"
      - "word_usage_h"
      - "word_usage_i"
      - "word_usage_j"
      - "word_usage_k"
      - "word_usage_l"
      - "word_usage_m"
      - "word_usage_n"
      - "word_usage_o"
      - "word_usage_p"
      - "word_usage_q"
      - "word_usage_r"
      - "word_usage_s"
      - "word_usage_t"
      - "word_usage_u"
      - "word_usage_v"
      - "word_usage_w"
      - "word_usage_x"
      - "word_usage_y"
      - "word_usage_z"
      - "anthropomorphism"
      - "capitalization"
      - "contractions"
      - "prefixes"
      - "plurals"
      - "spelling"
      - "terminology"
      - "abbreviations"
      - "technical_commands"
      - "technical_files_directories"
      - "technical_keyboard_keys"
      - "technical_mouse_buttons"
      - "technical_programming_elements"
      - "technical_ui_elements"
      - "technical_web_addresses"
  
  low:
    name: "Style Pass"
    display_name: "Style Pass"
    description: "Style refinements and polish"
    priority_level: 4
    color: "blue"
    icon: "fas fa-paint-brush"
    categories: ["citations", "currency", "pronouns", "ambiguity", "punctuation", "tone"]
    error_types:
      - "citations"
      - "currency"
      - "pronouns"
      - "ambiguity"
      - "punctuation_commas"
      - "punctuation_periods"
      - "punctuation_semicolons"
      - "punctuation_colons"
      - "punctuation_quotation_marks"
      - "punctuation_apostrophes"
      - "punctuation_hyphens"
      - "punctuation_dashes"
      - "punctuation_parentheses"
      - "punctuation_brackets"
      - "punctuation_ellipses"
      - "punctuation_slashes"
      - "punctuation_and_symbols"
      - "tone"
      - "references_citations"
      - "references_geographic_locations"
      - "references_names_titles"
      - "references_product_names"
      - "references_product_versions"

# Dynamic Station Configuration
# Stations are only shown when relevant errors are present
dynamic_stations:
  enabled: true
  show_empty_stations: false
  contextual_descriptions: true
  estimated_time_per_error: 3
  base_processing_time: 15

# Comprehensive instruction templates covering ALL rule types
instruction_templates:
  # ===== LEGAL/CRITICAL (URGENT) =====
  legal_claims: "Replace subjective claims with objective statements. Common fixes: 'easy' → 'straightforward', 'simple' → 'direct', 'great' → 'useful'. Output ONLY the corrected text."
  legal_company_names: "Fix company name formatting according to legal requirements. Use proper trademark symbols where required. Output ONLY the corrected text."
  legal_personal_information: "Replace specific personal information terms with generic equivalents while preserving meaning. 'first name and last name' → 'given name and surname', 'your name' → 'a name'. Keep the functional requirement. Output ONLY the corrected text."
  inclusive_language: "Replace non-inclusive terms with inclusive alternatives. Common fixes: 'guys' → 'everyone', 'man-hours' → 'person-hours'. Output ONLY the corrected text."
  second_person: "Remove first-person 'we/our' and use second person 'you' for user actions. Change 'We will' → 'You can', 'Our system' → 'The system'. Output ONLY the corrected text."
  
  # ===== STRUCTURAL (HIGH) =====
  passive_voice: "Convert passive voice to active voice. Make no other changes."
  sentence_length: "Break long sentence into shorter sentences. Make no other changes."
  subjunctive_mood: "Convert subjunctive mood to imperative. Change 'It is important that X be done' to 'Important: Do X'. Make no other changes."
  verbs: "Convert passive voice to active voice, but CRITICALLY: specify a CLEAR, LOGICAL actor. NEVER use vague actors like 'system', 'application', or 'software'. For UI text, use 'you' (user action) or specific component names. For instructions, use imperative mood ('Click the button' not 'The system clicks'). For technical docs, identify the actual responsible component. Preserve meaning and avoid ALL ambiguous actors. Output ONLY the corrected sentence."
  headings: "Fix heading capitalization and structure. Make no other changes."
  
  # ===== LANGUAGE & GRAMMAR (MEDIUM) =====
  abbreviations: "Fix abbreviation formatting and usage according to style guide. Replace Latin abbreviations like 'etc.' with English equivalents like 'and so on'. Ensure abbreviations are defined on first use. Make no other changes."
  adverbs_only: "Remove unnecessary adverbs or replace with stronger verbs. Make no other changes."
  anthropomorphism: "Remove anthropomorphism. Change 'system wants' → 'system requires', 'system thinks' → 'system determines', 'system feels' → 'system indicates'. Output ONLY the corrected text."
  articles: "Fix article usage (a, an, the) according to grammar rules. Make no other changes."
  capitalization: "Fix capitalization issues according to style guide. Make no other changes."
  conjunctions: "Fix conjunction usage and placement. Make no other changes."
  contractions: "Expand all contractions in formal writing. Common fixes: 'you'll' → 'you will', 'it's' → 'it is', 'can't' → 'cannot', 'don't' → 'do not'. Use comprehensive detection to catch any apostrophe-containing contractions. Make no other changes."
  plurals: "Fix parenthetical plurals. Change 'file(s)' to 'files'. Make no other changes."
  possessives: "Fix possessive forms and apostrophe usage. Make no other changes."
  prepositions: "Fix preposition usage and placement. Make no other changes."
  pronouns: "Replace ambiguous pronouns with specific nouns from the context. 'It is important that the configuration be saved' → 'The configuration must be saved'. Preserve the subject and meaning. Output ONLY the corrected sentence with NO explanations."
  spelling: "Fix spelling errors according to preferred dictionary. Make no other changes."
  terminology: "Replace non-preferred terms with approved terminology. Make no other changes."
  
  # ===== ENHANCED MORPHOLOGICAL RULES =====
  prefixes: "Remove hyphens from closed prefixes. Common fixes: 're-start' → 'restart', 'pre-set' → 'preset', 'non-standard' → 'nonstandard', 'multi-user' → 'multiuser'. Only change prefixes that should be closed according to style guidelines. Output ONLY the corrected text."
  
  # ===== WORD USAGE (A-Z) - All alphabet rules =====
  word_usage_a: "Replace problematic words as specified. Common fixes: 'allow' → 'enable', 'appears' → 'is displayed'. Output ONLY the corrected text."
  word_usage_b: "Replace problematic words as specified. Enhanced backup/back up analysis: Use 'backup' (one word) for nouns/adjectives and 'back up' (two words) for verbs. Examples: 'I need to backup the files' → 'I need to back up the files', 'Create a back up copy' → 'Create a backup copy'. Other fixes: 'below' → 'following', 'basically' → remove. Output ONLY the corrected text."
  word_usage_c: "Replace problematic words as specified. Common fixes: 'click' → 'select', 'currently' → remove. Output ONLY the corrected text."
  word_usage_d: "Replace problematic words as specified. Common fixes: 'desired' → 'required', 'displays' → 'shows'. Output ONLY the corrected text."
  word_usage_e: "Replace problematic words as specified. Common fixes: 'easy' → 'straightforward', 'enter' → 'type'. Output ONLY the corrected text."
  word_usage_f: "Replace problematic words as specified. Common fixes: 'feel free' → remove, 'functionality' → 'function'. Output ONLY the corrected text."
  word_usage_g: "Replace problematic words as specified. Common fixes: 'go to' → 'navigate to', 'great' → 'useful'. Output ONLY the corrected text."
  word_usage_h: "Replace problematic words as specified. Common fixes: 'hit' → 'press', 'however' → 'but'. Output ONLY the corrected text."
  word_usage_i: "Replace problematic words as specified. Common fixes: 'input' → 'enter', 'in order to' → 'to'. Output ONLY the corrected text."
  word_usage_j: "Replace problematic words as specified. Common fixes: 'just' → remove, 'jump to' → 'go to'. Output ONLY the corrected text."
  word_usage_k: "Replace problematic words as specified. Common fixes: 'kill' → 'stop', 'key in' → 'enter'. Output ONLY the corrected text."
  word_usage_l: "Replace problematic words as specified. Common fixes: 'login' → 'log in' (verb), 'lots of' → 'many'. Output ONLY the corrected text."
  word_usage_m: "Replace problematic words as specified. Common fixes: 'make sure' → 'ensure', 'may' → 'might'. Output ONLY the corrected text."
  word_usage_n: "Replace problematic words as specified. Common fixes: 'new' → remove if redundant, 'now' → remove if unnecessary. Output ONLY the corrected text."
  word_usage_o: "Replace problematic words as specified. Common fixes: 'obviously' → remove, 'ok' → 'acceptable'. Output ONLY the corrected text."
  word_usage_p: "Replace problematic words as specified. Common fixes: 'please' → remove, 'pretty' → remove. Output ONLY the corrected text."
  word_usage_q: "Replace problematic words as specified. Common fixes: 'quickly' → remove, 'quite' → remove. Output ONLY the corrected text."
  word_usage_r: "Replace problematic words as specified. Common fixes: 'really' → remove, 'right-click' → 'secondary-click'. Output ONLY the corrected text."
  word_usage_s: "Replace problematic words as specified. Common fixes: 'setup' (noun) → 'set up' (verb), 'simply' → remove. Output ONLY the corrected text."
  word_usage_t: "Replace problematic words as specified. Common fixes: 'that' (unnecessary) → remove, 'turn on' → 'enable'. Output ONLY the corrected text."
  word_usage_u: "Replace problematic words as specified. Common fixes: 'utilize' → 'use', 'update' → 'modify'. Output ONLY the corrected text."
  word_usage_v: "Replace problematic words as specified. Common fixes: 'very' → remove, 'via' → 'through'. Output ONLY the corrected text."
  word_usage_w: "Replace problematic words as specified. Common fixes: 'want' → 'need', 'will' → 'can'. Output ONLY the corrected text."
  word_usage_x: "Replace problematic words as specified. Common fixes: 'x out' → 'close', 'x-ing' → proper term. Output ONLY the corrected text."
  word_usage_y: "Replace problematic words as specified. Common fixes: 'you can' → direct instruction, 'yet' → 'but'. Output ONLY the corrected text."
  word_usage_z: "Replace problematic words as specified. Common fixes: 'zip' → 'compress', 'zero out' → 'clear'. Output ONLY the corrected text."
  word_usage_special: "Fix usage of special characters and symbols as specified. Output ONLY the corrected text."
  
  # ===== PUNCTUATION =====
  colons: "Fix colon usage and placement according to style guide. Make no other changes."
  commas: "Fix comma usage and placement according to style guide. Make no other changes."
  dashes: "Fix dash usage (em dash, en dash) according to style guide. Make no other changes."
  ellipses: "Fix ellipsis usage and formatting. Make no other changes."
  exclamation_points: "Remove exclamation points from technical writing. Replace with periods. 'Save it!' → 'Save it.' Output ONLY the corrected text."
  hyphens: "Fix hyphen usage in compound words and modifiers. Make no other changes."
  parentheses: "Fix parentheses usage and placement. Make no other changes."
  periods: "Fix period usage and placement. Make no other changes."
  punctuation_and_symbols: "Fix general punctuation and symbol usage. Make no other changes."
  quotation_marks: "Fix quotation mark usage and placement. Make no other changes."
  semicolons: "Fix semicolon usage and placement. Make no other changes."
  slashes: "Fix slash usage and formatting. Make no other changes."
  
  # ===== NUMBERS & MEASUREMENT =====
  numbers_currency: "Replace currency symbols with ISO codes. Change '$' → 'USD', '€' → 'EUR', '£' → 'GBP'. Output ONLY the corrected text."
  dates_and_times: "Fix date and time formatting according to style guide. Make no other changes."
  numbers_general: "Fix number formatting and usage according to style guide. Make no other changes."
  numerals_vs_words: "Fix when to use numerals vs spelled-out numbers. Make no other changes."
  units_of_measurement: "Fix unit of measurement formatting and abbreviations. Make no other changes."
  
  # ===== AUDIENCE & MEDIUM =====
  conversational_style: "Adjust tone to be appropriately conversational but professional. Make no other changes."
  global_audiences: "Replace culturally specific terms with globally understood alternatives. Make no other changes."
  llm_consumability: "Improve text structure for AI/LLM processing clarity. Make no other changes."
  tone: "Adjust tone to match the target audience and content type. Make no other changes."
  
  # ===== TECHNICAL ELEMENTS =====
  technical_commands: "Fix formatting of command names and syntax. Make no other changes."
  technical_files_directories: "Fix formatting of file and directory paths. Make no other changes."
  technical_keyboard_keys: "Fix formatting of keyboard key references. Make no other changes."
  technical_mouse_buttons: "Fix formatting of mouse button references. Make no other changes."
  technical_programming_elements: "Fix formatting of code elements and programming terms. Make no other changes."
  technical_ui_elements: "Fix formatting of user interface element references. Make no other changes."
  technical_web_addresses: "Fix formatting of URLs and web addresses. Make no other changes."
  
  # ===== REFERENCES =====
  references_citations: "Replace 'click here' with meaningful link text that describes the destination. Examples: 'click here' → 'see the documentation', 'for details, click here' → 'for details, see the user guide'. Output ONLY the corrected sentence."
  references_geographic_locations: "Fix geographic location formatting and abbreviations. Make no other changes."
  references_names_titles: "Fix person name and title formatting. Make no other changes."
  references_product_names: "Fix product name formatting and capitalization. Make no other changes."
  references_product_versions: "Fix product version formatting and notation. Make no other changes."
  
  # ===== STRUCTURE & FORMAT =====
  examples: "Fix example formatting and presentation. Make no other changes."
  glossaries: "Fix glossary term formatting and definitions. Make no other changes."
  highlighting: "Fix text highlighting and emphasis formatting. Make no other changes."
  lists: "Fix list formatting, parallelism, and structure. Make no other changes."
  procedures: "Fix procedure step formatting and numbering. Make no other changes."
  notes: "Fix note and admonition formatting. Make no other changes."
  structure_format_notes: "Fix note and admonition formatting. Make no other changes."
  
  # ===== GENERAL RULES =====
  ambiguity: "Replace unclear pronouns like 'This', 'It', 'That' with specific nouns. Example: 'This is easy' → 'The process is easy'. Output ONLY the corrected sentence with NO explanations."
  
  # ===== PATTERN MATCHERS (Fallbacks) =====
  word_usage_*: "Fix word usage issues. Replace incorrect terms with preferred alternatives. Return ONLY the corrected sentence with NO explanations."
  punctuation_*: "Fix punctuation issues according to style guide. Make no other changes."
  numbers_*: "Fix number formatting according to style guide. Make no other changes."
  technical_*: "Fix technical element formatting according to style guide. Make no other changes."
  references_*: "Fix reference formatting according to style guide. Make no other changes."
  structure_*: "Fix structural formatting according to style guide. Make no other changes."
  legal_*: "Fix legal compliance issues. Make no other changes."
  prefix_*: "Fix prefix hyphenation according to style guide. Remove hyphens from closed prefixes. Make no other changes."

# Quality preservation rules (applied to ALL fixes)
quality_preservation:
  - "Preserve all functional requirements and specific information"
  - "Do not lose important details or context"
  - "Avoid creating new ambiguous pronouns" 
  - "Do not add exclamation points in technical writing"
  - "Keep changes minimal and surgical"
  - "Maintain the original intent and meaning"

# Enhanced processing for new rule types
enhanced_rules:
  prefixes:
    priority: "medium"
    description: "Morphological prefix analysis using spaCy"
    examples:
      - "re-start → restart"
      - "pre-configure → preconfigure" 
      - "non-essential → nonessential"
      
  enhanced_contractions:
    priority: "medium"
    description: "Comprehensive contraction detection using regex patterns"
    examples:
      - "you'll → you will"
      - "it's → it is"
      - "can't → cannot"
      
  enhanced_word_usage_b:
    priority: "medium"
    description: "Advanced backup vs back up morphological analysis"
    examples:
      - "backup the system (verb) → back up the system"
      - "create a back up (noun) → create a backup"

# Fallback instruction for unknown error types
fallback_instruction: "Fix {error_type} issues according to the style guide. Make minimal changes to preserve meaning and context. Do not lose important information."

# Severity to priority mapping
severity_mapping:
  high: urgent
  medium: high  
  low: medium 