---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: languagetool
  labels:
    app: languagetool
    app.kubernetes.io/name: languagetool
    app.kubernetes.io/component: grammar-checker
    app.kubernetes.io/part-of: cea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languagetool
  template:
    metadata:
      labels:
        app: languagetool
    spec:
      containers:
        - name: languagetool
          image: quay.io/rhdeveldocs/languagetool:6.7-ngram-v1
          ports:
            - containerPort: 8010
              protocol: TCP
          env:
            - name: Java_Xms
              value: "512m"
            - name: Java_Xmx
              value: "3g"
            - name: langtool_languageModel
              value: "/ngrams"
          resources:
            requests:
              memory: "10Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "2"
          startupProbe:
            httpGet:
              path: /v2/languages
              port: 8010
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/languages
              port: 8010
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v2/languages
              port: 8010
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
