---
apiVersion: v1
kind: Service
metadata:
  name: languagetool
  labels:
    app: languagetool
    app.kubernetes.io/name: languagetool
    app.kubernetes.io/component: grammar-checker
    app.kubernetes.io/part-of: cea
spec:
  type: ClusterIP
  selector:
    app: languagetool
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      name: http
