# Indentation Rule Configuration
# Comprehensive patterns for indentation issue detection with evidence-based scoring

indentation_violations:
  
  # === MIXED INDENTATION ===
  mixed_indentation:
    pattern: "^(\\t+ +| +\\t+)"
    evidence: 0.9
    severity: "medium"
    message: "Mixed tabs and spaces in indentation"
    description: "Consistent indentation improves code readability and prevents errors"
    
  # === ODD INDENTATION LEVELS ===
  odd_indentation:
    pattern: "^( {1}[^ ]| {3}[^ ]| {5}[^ ]| {7}[^ ])"
    evidence: 0.6
    severity: "low"
    message: "Unusual indentation spacing detected"
    description: "Standard indentation uses 2, 4, or 8 spaces"
    
  # === EXCESSIVE INDENTATION ===
  excessive_indentation:
    pattern: "^( {9,}|\\t{3,})(\\S)"
    evidence: 0.7
    severity: "medium"
    message: "Excessive indentation depth"
    description: "Very deep indentation can reduce readability"
    
  # === ACCIDENTAL SINGLE SPACE ===
  accidental_single_space:
    pattern: "^( {1})([A-Z][a-z])"
    evidence: 0.8
    severity: "medium"
    message: "Accidental space at beginning of line"
    description: "Single space before capital letter likely unintentional"
    
  # === UNUSUAL WHITESPACE ===
  unusual_whitespace:
    pattern: "^[\\u00A0\\u1680\\u2000-\\u200B\\u202F\\u205F\\u3000\\uFEFF]+"
    evidence: 0.9
    severity: "medium"
    message: "Unusual or invisible whitespace characters"
    description: "Non-standard whitespace can cause display and processing issues"

# === STANDARD INDENTATION LEVELS ===
standard_indentations:
  recommended_levels: [2, 4, 8]  # Standard indentation levels in spaces
  tab_equivalent: 4              # Treat tabs as 4 spaces for comparison
  maximum_depth: 8               # Maximum reasonable indentation depth

# === CONTEXT EXCEPTIONS ===
# Contexts where indentation rules should be more permissive or skipped

context_exceptions:
  
  # Code contexts - indentation controlled by other tools
  code_blocks: -1.0              # Completely skip code blocks
  inline_code: -1.0              # Skip inline code
  literal_blocks: -1.0           # Skip literal blocks
  
  # Table contexts - alignment may use intentional spacing
  table_cells: -0.8              # Very permissive for table alignment
  table_headers: -0.8
  
  # Creative contexts - intentional formatting allowed
  poetry: -0.9                   # Poetry may use intentional indentation
  verse: -0.9
  creative_writing: -0.6         # Creative writing more flexible
  
  # Quote contexts - preserve original formatting
  blockquotes: -0.7              # Quotes may preserve original indentation
  citations: -0.5
  
  # List contexts - expected indentation variation
  nested_lists: -0.3             # Nested lists have expected indentation
  definition_lists: -0.4         # Definition lists use special formatting
  
  # Special formatting contexts
  ascii_art: -1.0                # ASCII art requires precise spacing
  diagrams: -1.0                 # Diagrams need custom spacing
  forms: -0.8                    # Forms may use alignment spacing

# === EVIDENCE ADJUSTMENTS ===
# Fine-tune evidence scoring based on specific conditions

evidence_adjustments:
  
  # Content type adjustments
  technical_documentation: 0.1   # Technical docs should have consistent indentation
  formal_documents: 0.1          # Formal docs need proper formatting
  user_guides: 0.0               # User guides neutral
  reference_material: -0.1       # Reference material more flexible
  
  # Document structure adjustments
  headings:
    level_1: 0.1                 # H1 headings highly visible
    level_2: 0.05                # H2 headings visible
    level_3_plus: 0.0            # Lower level headings neutral
    
  paragraphs: 0.0                # Standard paragraph indentation rules
  
  list_items:
    top_level: 0.05              # Top-level lists more visible
    nested_level1: 0.0           # First level nesting neutral
    nested_level2: -0.1          # Deeper nesting more permissive
    deeply_nested: -0.2          # Very deep nesting very permissive
  
  # Pattern-specific adjustments
  pattern_combinations:
    mixed_with_excessive: 0.2    # Mixed indentation + excessive depth is worse
    odd_with_inconsistent: 0.1   # Odd spacing + inconsistency compounds issues
    
  # Length-based adjustments
  document_length:
    short_content: -0.1          # Short content more permissive
    medium_content: 0.0          # Medium content neutral
    long_content: 0.1            # Long content needs consistency

# === CONSISTENCY ANALYSIS ===
# Settings for analyzing indentation consistency across documents

consistency_analysis:
  
  minimum_lines_for_analysis: 5  # Need at least 5 indented lines to analyze
  consistency_threshold: 0.7     # 70% of lines should follow same pattern
  
  pattern_detection:
    min_occurrences: 3           # Need 3+ occurrences to establish pattern
    ignore_single_occurrences: true
    
  inconsistency_penalties:
    pattern_count_2: 0.0         # 2 patterns might be acceptable
    pattern_count_3: 0.3         # 3+ patterns suggest inconsistency
    pattern_count_4_plus: 0.5    # Many patterns clearly inconsistent
    
  mixed_indentation_penalties:
    tabs_and_spaces: 0.4         # Strong penalty for mixing tabs/spaces
    varied_space_counts: 0.2     # Penalty for multiple space counts

# === SUGGESTION TEMPLATES ===
# Context-aware suggestion templates for different violation types

suggestion_templates:
  
  mixed_indentation:
    high_confidence:
      - "Use consistent indentation (either tabs or spaces, not both)"
      - "Configure your editor to show whitespace characters"
      - "Choose spaces for better cross-platform compatibility"
    medium_confidence:
      - "Consider standardizing on tabs or spaces for indentation"
      - "Check your editor's indentation settings"
    low_confidence:
      - "Review indentation consistency in this section"
      
  odd_indentation:
    high_confidence:
      - "Use standard indentation levels (2, 4, or 8 spaces)"
      - "Align content with established spacing patterns"
      - "Check if this indentation serves a specific purpose"
    medium_confidence:
      - "Consider using standard indentation increments"
      - "Review indentation for consistency"
    low_confidence:
      - "This indentation spacing may be unusual"
      
  excessive_indentation:
    high_confidence:
      - "Reduce indentation depth for better readability"
      - "Consider restructuring deeply nested content"
      - "Very deep indentation can be hard to follow"
    medium_confidence:
      - "This content may be too deeply indented"
      - "Consider flattening the structure if possible"
    low_confidence:
      - "Review whether this indentation depth is necessary"
      
  accidental_single_space:
    high_confidence:
      - "Remove the accidental space at the beginning of the line"
      - "This appears to be unintentional leading whitespace"
      - "Use proper indentation if nesting is intended"
    medium_confidence:
      - "Check if this leading space is intentional"
      - "Consider removing if not needed for formatting"
    low_confidence:
      - "Review leading whitespace on this line"
      
  inconsistent_indentation:
    high_confidence:
      - "Use consistent indentation throughout the document"
      - "Establish a single indentation standard and apply it consistently"
      - "Mixed indentation patterns reduce readability"
    medium_confidence:
      - "Consider standardizing indentation across sections"
      - "Review indentation patterns for consistency"
    low_confidence:
      - "Some indentation inconsistency detected"

# === FORMATTING GUIDELINES ===
# Best practices and recommendations for indentation

formatting_guidelines:
  
  recommended_practices:
    - "Use either tabs or spaces consistently, never mix them"
    - "Choose 2, 4, or 8 spaces for standard indentation"
    - "Keep indentation depth reasonable (typically 6 levels max)"
    - "Use your editor's 'Show Whitespace' feature to see indentation"
    - "Configure your editor for consistent indentation"
    
  editor_configurations:
    vscode: "editor.renderWhitespace: all, editor.detectIndentation: false"
    sublime: "draw_white_space: all, translate_tabs_to_spaces: true"
    vim: "set list, set expandtab, set tabstop=4"
    emacs: "whitespace-mode, indent-tabs-mode: nil"
    
  document_types:
    markdown:
      - "Use spaces for indentation in Markdown"
      - "Lists typically use 2 or 4 spaces"
      - "Code blocks use 4 spaces or triple backticks"
    asciidoc:
      - "AsciiDoc is flexible with indentation"
      - "Use consistent spacing for list nesting"
      - "Source code blocks should maintain original indentation"
    restructuredtext:
      - "reStructuredText is whitespace-sensitive"
      - "Use consistent indentation for directives"
      - "Maintain alignment in complex structures"

# === PERFORMANCE SETTINGS ===
performance:
  max_lines_analyzed: 1000       # Limit analysis for very long documents
  enable_consistency_analysis: true
  cache_indentation_patterns: true
  
  # Skip analysis conditions
  skip_very_short_content: true   # Skip content with < 3 lines
  skip_single_line_content: true  # Skip single-line content
  
  # Analysis depth
  full_document_analysis: true    # Analyze entire document for consistency
  per_section_analysis: false     # Don't analyze sections independently

# === QUALITY ASSURANCE ===
quality_assurance:
  
  false_positive_prevention:
    respect_intentional_formatting: true
    preserve_creative_indentation: true
    allow_table_alignment: true
    skip_ascii_art: true
    
  evidence_validation:
    minimum_confidence_threshold: 0.2
    require_pattern_confirmation: true
    cross_validate_with_context: true
    
  error_consolidation:
    group_similar_violations: true
    prioritize_most_severe: true
    limit_errors_per_section: 5
