# Programming Elements Rule Configuration
# Production-grade YAML configuration for programming keyword patterns
# Evidence-based scoring with context adjustments

# Programming Keywords - Keywords that shouldn't be used as verbs
programming_keywords:
  sql_keywords:
    - keyword: "select"
      evidence: 0.85
      category: "sql_command"
      description: "SQL keyword used as verb"
      legitimate_patterns: ["select statement", "select query", "sql select", "select command", "select a", "select an", "select from"]
      
    - keyword: "insert"
      evidence: 0.85
      category: "sql_command"
      description: "SQL keyword used as verb"
      legitimate_patterns: ["insert statement", "insert query", "sql insert", "insert command", "insert a", "insert an", "insert into"]
      
    - keyword: "update"
      evidence: 0.85
      category: "sql_command"
      description: "SQL keyword used as verb"
      legitimate_patterns: ["update statement", "update query", "sql update", "update command", "keep updated", "stay updated", "regularly update", "update your", "update the", "update information", "update status", "update progress", "update settings", "update profile"]
      
    - keyword: "delete"
      evidence: 0.85
      category: "sql_command"
      description: "SQL keyword used as verb"
      legitimate_patterns: ["delete statement", "delete query", "sql delete", "delete command", "delete files", "delete manually", "delete content", "delete permanently", "delete selected", "delete all"]

  language_keywords:
    - keyword: "import"
      evidence: 0.8
      category: "language_keyword"
      description: "Programming keyword used as verb"
      legitimate_patterns: ["import statement", "import module", "import package", "import library"]
      
    - keyword: "export"
      evidence: 0.8
      category: "language_keyword"
      description: "Programming keyword used as verb"
      legitimate_patterns: ["export statement", "export function", "export module", "export data"]
      
    - keyword: "return"
      evidence: 0.7
      category: "language_keyword"
      description: "Programming keyword used as verb"
      legitimate_patterns: ["return statement", "return value", "function returns", "method returns", "returns a", "returns an", "returns the", "returns data", "returns object", "return home", "return items", "return call", "return later", "return policy", "function will return", "method will return", "will return a", "will return the", "return the result"]
      
    - keyword: "throw"
      evidence: 0.75
      category: "language_keyword"
      description: "Programming keyword used as verb"
      legitimate_patterns: ["throw statement", "throw exception", "throw error"]
      
    - keyword: "catch"
      evidence: 0.7
      category: "language_keyword"
      description: "Programming keyword used as verb"
      legitimate_patterns: ["catch block", "catch exception", "catch error", "try catch"]

  api_keywords:
    - keyword: "execute"
      evidence: 0.6
      category: "api_keyword"
      description: "API keyword used as verb"
      legitimate_patterns: ["execute command", "execute function", "execute query", "execute script"]
      
    - keyword: "invoke"
      evidence: 0.7
      category: "api_keyword"
      description: "API keyword used as verb"
      legitimate_patterns: ["invoke method", "invoke function", "invoke api"]
      
    - keyword: "call"
      evidence: 0.4
      category: "api_keyword"
      description: "API keyword used as verb (low confidence due to common usage)"
      legitimate_patterns: ["api call", "function call", "method call", "call function", "call api", "phone call", "call support", "call meeting"]

# Context Adjustments
context_adjustments:
  content_type:
    technical: 0.0
    api: 0.0
    tutorial: -0.1
    
  audience:
    developer: 0.0
    general: 0.1

# === ENHANCED: LINGUISTIC INTELLIGENCE CONFIGURATION ===

linguistic_guards:
  # Programming context indicators - used multiple times in guards
  programming_context_indicators:
    - "database"
    - "table" 
    - "record"
    - "row"
    - "column"
    - "schema"
    - "query"
    - "sql"
    - "mysql"
    - "postgresql"
    - "mongodb"
    - "nosql"
    - "server"
    - "system" 
    - "repository"
    - "code"
    - "script"
    - "program"
    - "application"
    - "software"
    - "api"
    - "function"
    - "method"
    - "object"
    - "class"
    - "variable"
    - "array"
    - "commit"
    - "branch"
    - "merge"
    - "deploy"
    - "build"
    - "client"
    - "backend"
    - "frontend"
    - "framework"

  # Programming objects that should trigger flagging
  programming_objects:
    database_objects:
      - "database"
      - "table"
      - "record" 
      - "row"
      - "column"
      - "index"
      - "schema"
      - "query"
      - "view"
      - "procedure"
      - "trigger"
      - "constraint"
    
    programming_objects:
      - "object"
      - "instance"
      - "variable"
      - "array"
      - "list"
      - "dictionary"
      - "function"
      - "method"
      - "class"
      - "module"
      - "package"
    
    system_objects:
      - "file"
      - "directory"
      - "path"
      - "config"
      - "setting"
      - "parameter"
      - "service"
      - "process"
      - "thread"
      - "connection"
      - "system"
      - "server"
      - "repository"

  # Non-programming objects that indicate business/general usage
  non_programming_objects:
    documents_content:
      - "document"
      - "content"
      - "text"
      - "image"
      - "report"
      - "form"
      - "page"
      - "section"
      - "chapter"
      - "documentation"
    
    people_organizations:
      - "user"
      - "person"
      - "team"
      - "business"
      - "company"
      - "organization"
      - "client"
      - "customer"
      - "employee"
      - "member"
      - "group"
      - "department"
    
    business_objects:
      - "profile"
      - "account"
      - "order"
      - "invoice"
      - "contract"
      - "agreement"
      - "policy"
      - "procedure"
      - "process"
      - "workflow"
      - "schedule"
      - "meeting"
      - "project"
      - "task"
      - "goal"
      - "objective"
      - "plan"
      - "strategy"

  # Infinitive detection verbs
  infinitive_verbs:
    - "need"
    - "want"
    - "try"
    - "plan"
    - "decide"
    - "choose"
    - "attempt"
    - "expect"
    - "hope"
    - "prefer"

  # General context indicators for imperative analysis
  general_context_indicators:
    - "documentation"
    - "information"
    - "profile"
    - "settings"
    - "preferences"
    - "account"
    - "user"
    - "team"
    - "business"
    - "process"
    - "procedure"

# Programming pattern templates (dynamic with keyword substitution)
programming_patterns:
  templates:
    - "{keyword} the database"
    - "{keyword} a table"
    - "{keyword} the table"
    - "{keyword} records"
    - "{keyword} data"
    - "{keyword} the system"
    - "{keyword} the server"
    - "{keyword} the repository"
    - "{keyword} configuration"
    - "{keyword} parameters"

# Evidence scoring adjustments
evidence_adjustments:
  programming_context_boost: 0.2
  imperative_command_boost: 0.15
  technical_object_boost: 0.25
  programming_pattern_boost: 0.2
  technical_preposition_boost: 0.15

# Thresholds and Messages
thresholds:
  detection_threshold: 0.1
  high_confidence: 0.8

messages:
  high_confidence:
    template: "Programming keyword '{keyword}' is being used as a verb. Use proper programming syntax instead."

suggestions:
  high_confidence:
    - "Use proper programming syntax: 'Use the {keyword} statement'"
    - "Consider: 'Execute {keyword} to...'"

# Passive voice patterns - legitimate uses of programming keywords in passive constructions
passive_voice_patterns:
  # Auxiliary verbs that indicate passive voice constructions
  auxiliary_verbs:
    - "be"
    - "is"
    - "am" 
    - "are"
    - "was"
    - "were"
    - "been"
    - "being"
  
  # Common legitimate passive patterns in technical writing
  legitimate_patterns:
    - "error is thrown"
    - "exception is thrown"
    - "timeout error is thrown"
    - "data is selected"
    - "records are selected"
    - "file is deleted"
    - "table is updated"
    - "query is executed"
    - "function is called"
    - "method is invoked"
    - "process is terminated"
    - "connection is closed"
  
  # Context indicators that suggest passive voice is appropriate
  appropriate_contexts:
    - "system behavior descriptions"
    - "error condition explanations"
    - "process documentation"
    - "technical specifications"
    - "API documentation"

guard_patterns:
  code_blocks: true
  inline_code: true
  literal_blocks: true
