# Llama Stack Configuration for Content Editorial Assistant

version: '2'
image_name: cea-llamastack
apis:
  - inference
server:
  tls_certfile: ${env.LIGHTRAIL_LLAMA_STACK_TLS_CERT_PATH:}
  tls_keyfile: ${env.LIGHTRAIL_LLAMA_STACK_TLS_KEY_PATH:}
providers:
  inference:
    - provider_id: vllm-inference
      provider_type: remote::vllm
      config:
        url: ${env.CEA_MODEL_BASE_URL}
        api_token: ${env.CEA_MODEL_API_TOKEN}
        tls_verify: ${env.LIGHTRAIL_LLAMA_STACK_TLS_CA_CERT_PATH}
models:
  - provider_id: vllm-inference
    model_id: ${env.CEA_MODEL_ID}
    model_type: llm
    metadata: {}
