"""PDF Report Generator for Content Editorial Assistant.

Produces a crisp 2-3 page executive summary PDF using ReportLab.
Renders exclusively from metrics, charts, and issue breakdown —
no full document text is included (Trap 3 guard).
"""

import io
import logging
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# ── Colour palette ────────────────────────────────────────────────────

_GREEN = colors.HexColor("#1A8F57")
_BLUE = colors.HexColor("#0066CC")
_ORANGE = colors.HexColor("#F2BA4D")
_RED = colors.HexColor("#C9190B")
_GREY = colors.HexColor("#6A6E73")
_LIGHT_GREY = colors.HexColor("#F0F0F0")
_WHITE = colors.white


def _score_color(score: int) -> colors.Color:
    """Map a 0-100 score to a semantic colour."""
    if score >= 90:
        return _GREEN
    if score >= 75:
        return _BLUE
    if score >= 60:
        return _ORANGE
    return _RED


def _score_label(score: int) -> str:
    """Map a 0-100 score to a human label."""
    if score >= 90:
        return "Excellent"
    if score >= 75:
        return "Good"
    if score >= 60:
        return "Needs Work"
    return "Requires Revision"


# ── Styles ────────────────────────────────────────────────────────────

def _build_styles() -> dict[str, ParagraphStyle]:
    """Create the PDF paragraph styles."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "CEA_Title", parent=base["Title"],
            fontSize=20, leading=24, spaceAfter=6,
            textColor=colors.HexColor("#151515"),
        ),
        "subtitle": ParagraphStyle(
            "CEA_Subtitle", parent=base["Normal"],
            fontSize=10, leading=14, spaceAfter=16,
            textColor=_GREY,
        ),
        "heading": ParagraphStyle(
            "CEA_Heading", parent=base["Heading2"],
            fontSize=13, leading=16, spaceBefore=18, spaceAfter=8,
            textColor=colors.HexColor("#151515"),
        ),
        "body": ParagraphStyle(
            "CEA_Body", parent=base["Normal"],
            fontSize=10, leading=14, spaceAfter=6,
        ),
        "small": ParagraphStyle(
            "CEA_Small", parent=base["Normal"],
            fontSize=8, leading=10, textColor=_GREY,
        ),
        "score": ParagraphStyle(
            "CEA_Score", parent=base["Normal"],
            fontSize=36, leading=40, alignment=1,
        ),
        "score_label": ParagraphStyle(
            "CEA_ScoreLabel", parent=base["Normal"],
            fontSize=12, leading=16, alignment=1, textColor=_GREY,
        ),
    }


# ── Page elements ─────────────────────────────────────────────────────

def _add_footer(canvas: Any, doc: Any) -> None:
    """Draw footer on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_GREY)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    canvas.drawString(
        doc.leftMargin, 0.5 * inch,
        f"Generated by Content Editorial Assistant  |  {now}  |  "
        "AI-generated analysis \u2014 always review before use",
    )
    canvas.drawRightString(
        doc.pagesize[0] - doc.rightMargin, 0.5 * inch,
        f"Page {canvas.getPageNumber()}",
    )
    canvas.restoreState()


def _metric_table(
    data: list[list[str]],
    col_widths: list[float],
) -> Table:
    """Build a consistently styled data table."""
    table = Table(data, colWidths=col_widths)
    style_commands: list[tuple[str, ...]] = [
        ("BACKGROUND", (0, 0), (-1, 0), _LIGHT_GREY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#151515")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("LEADING", (0, 0), (-1, -1), 13),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D2D2D2")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]
    table.setStyle(TableStyle(style_commands))
    return table


# ── Public API ────────────────────────────────────────────────────────

def generate_pdf_report(
    report_data: dict[str, Any],
    score_data: dict[str, Any],
    issues_data: list[dict[str, Any]],
) -> bytes:
    """Generate a PDF report as bytes.

    Args:
        report_data: Serialized ReportResponse dict.
        score_data: Serialized ScoreResponse dict.
        issues_data: Serialized list of IssueResponse dicts (Trap 5 guard).

    Returns:
        PDF file content as bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.85 * inch,
    )

    styles = _build_styles()
    story: list[Any] = []

    # ── Page 1: Cover + Executive Summary ─────────────────────────
    story.append(Paragraph("Content Editorial Analysis Report", styles["title"]))

    stats = report_data.get("statistics", {})
    word_count = stats.get("word_count", report_data.get("word_count", 0))
    reading_time = stats.get("estimated_reading_time", "")
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
    story.append(Paragraph(
        f"{date_str}  |  {word_count:,} words  |  Reading time: {reading_time or 'N/A'}",
        styles["subtitle"],
    ))

    # Quality score
    score_val = int(score_data.get("score", 0))
    color = _score_color(score_val)
    label = _score_label(score_val)
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        f'<font color="{color.hexval()}">{score_val}</font>',
        styles["score"],
    ))
    story.append(Paragraph(
        f'<font color="{color.hexval()}">{label}</font>',
        styles["score_label"],
    ))
    story.append(Spacer(1, 12))

    # Key findings
    story.append(Paragraph("Key Findings", styles["heading"]))
    total_issues = int(score_data.get("total_issues", len(issues_data)))
    _add_key_findings(story, styles, report_data, total_issues, issues_data)

    story.append(HRFlowable(
        width="100%", thickness=0.5, color=_LIGHT_GREY,
        spaceBefore=12, spaceAfter=12,
    ))

    # ── Page 2: Metrics Dashboard ─────────────────────────────────
    _add_readability_section(story, styles, report_data)
    _add_llm_consumability_section(story, styles, report_data)
    _add_compliance_section(story, styles, report_data)
    _add_document_overview(story, styles, report_data)

    # ── Page 3: Issue Summary + Recommendations ───────────────────
    _add_issue_breakdown(story, styles, score_data)
    _add_recommendations(story, styles, issues_data)

    doc.build(story, onFirstPage=_add_footer, onLaterPages=_add_footer)
    return buf.getvalue()


# ── Section builders ──────────────────────────────────────────────────

def _add_key_findings(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    report_data: dict[str, Any],
    total_issues: int,
    issues_data: list[dict[str, Any]],
) -> None:
    """Add bullet-point key findings to the story."""
    bullets: list[str] = []

    if total_issues == 0:
        bullets.append("No editorial issues detected.")
    else:
        bullets.append(f"{total_issues} editorial issue(s) identified.")

    # Top category
    if issues_data:
        cats: dict[str, int] = {}
        for iss in issues_data:
            cat = str(iss.get("category", "unknown"))
            cats[cat] = cats.get(cat, 0) + 1
        top_cat = max(cats, key=cats.get)  # type: ignore[arg-type]
        bullets.append(
            f"Most common category: {top_cat.replace('_', ' ')} "
            f"({cats[top_cat]} issue(s)).",
        )

    # Readability
    readability = report_data.get("readability", {})
    flesch = readability.get("Flesch Reading Ease", {})
    flesch_score = float(flesch.get("score", 0))
    if flesch_score >= 60:
        bullets.append(
            f"Readability is strong (Flesch {flesch_score:.0f}) "
            "\u2014 accessible to a broad audience.",
        )
    elif flesch_score > 0:
        bullets.append(
            f"Readability could improve (Flesch {flesch_score:.0f}) "
            "\u2014 consider simplifying complex sentences.",
        )

    for b in bullets:
        story.append(Paragraph(f"\u2022  {b}", styles["body"]))


def _add_readability_section(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    report_data: dict[str, Any],
) -> None:
    """Add 4-metric readability table."""
    readability = report_data.get("readability", {})
    if not readability:
        return

    story.append(Paragraph("Readability Metrics", styles["heading"]))

    rows: list[list[str]] = [["Metric", "Score", "Ideal Range"]]
    ideal_ranges = {
        "Flesch Reading Ease": "60\u201370",
        "Flesch-Kincaid Grade": "8\u201312",
        "Gunning Fog": "8\u201312",
        "Coleman-Liau": "10\u201314",
    }
    for name, data in readability.items():
        score = float(data.get("score", 0))
        ideal = ideal_ranges.get(name, "\u2014")
        rows.append([name, f"{score:.1f}", ideal])

    if len(rows) > 1:
        story.append(_metric_table(rows, [3 * inch, 1.2 * inch, 1.5 * inch]))
        story.append(Spacer(1, 8))


def _add_llm_consumability_section(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    report_data: dict[str, Any],
) -> None:
    """Add LLM consumability score and dimension breakdown."""
    llm = report_data.get("llm_consumability", {})
    if not llm:
        return

    score = int(llm.get("score", 0))
    label = str(llm.get("label", ""))
    story.append(Paragraph("LLM Consumability", styles["heading"]))
    story.append(Paragraph(
        f"Score: <b>{score}/100</b> \u2014 {label}", styles["body"],
    ))

    dims = llm.get("dimensions", {})
    if dims:
        rows: list[list[str]] = [["Dimension", "Score"]]
        for key, dim_data in dims.items():
            dim_label = key.replace("_", " ").title()
            dim_score = int(dim_data.get("score", 0))
            rows.append([dim_label, str(dim_score)])
        story.append(_metric_table(rows, [4 * inch, 1.5 * inch]))
        story.append(Spacer(1, 8))


def _add_compliance_section(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    report_data: dict[str, Any],
) -> None:
    """Add style guide compliance percentages."""
    compliance = report_data.get("compliance", {})
    if not compliance:
        return

    labels = {
        "ibm_style": "IBM Style Guide",
        "red_hat_style": "Red Hat Style",
        "accessibility": "Accessibility",
        "modular_docs": "Modular Docs",
    }

    story.append(Paragraph("Style Guide Compliance", styles["heading"]))
    rows: list[list[str]] = [["Guide", "Compliance"]]
    for key, value in compliance.items():
        pct = round(float(value or 0) * 100)
        guide_label = labels.get(key, key.replace("_", " ").title())
        rows.append([guide_label, f"{pct}%"])

    story.append(_metric_table(rows, [4 * inch, 1.5 * inch]))
    story.append(Spacer(1, 8))


def _add_document_overview(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    report_data: dict[str, Any],
) -> None:
    """Add document statistics overview."""
    stats = report_data.get("statistics", {})
    if not stats:
        return

    story.append(Paragraph("Document Overview", styles["heading"]))
    rows: list[list[str]] = [["Metric", "Value"]]

    word_count = stats.get("word_count", 0)
    rows.append(["Words", f"{word_count:,}"])
    rows.append(["Sentences", str(stats.get("sentence_count", 0))])
    rows.append(["Paragraphs", str(stats.get("paragraph_count", 0))])
    rows.append(["Reading Time", stats.get("estimated_reading_time", "N/A")])
    rows.append(["Avg. Words/Sentence", f"{float(stats.get('avg_sentence_length', 0)):.1f}"])

    diversity = float(stats.get("vocabulary_diversity", 0))
    rows.append(["Vocabulary Diversity", f"{round(diversity * 100)}%"])

    story.append(_metric_table(rows, [4 * inch, 1.5 * inch]))
    story.append(Spacer(1, 8))


def _add_issue_breakdown(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    score_data: dict[str, Any],
) -> None:
    """Add issue category breakdown table."""
    cats = score_data.get("category_counts", {})
    if not cats:
        return

    story.append(Paragraph("Issue Breakdown by Category", styles["heading"]))
    rows: list[list[str]] = [["Category", "Count"]]
    for cat, count in sorted(cats.items(), key=lambda x: x[1], reverse=True):
        rows.append([cat.replace("_", " ").title(), str(count)])

    story.append(_metric_table(rows, [4 * inch, 1.5 * inch]))
    story.append(Spacer(1, 8))


def _add_recommendations(
    story: list[Any],
    styles: dict[str, ParagraphStyle],
    issues_data: list[dict[str, Any]],
) -> None:
    """Add top 5 priority recommendations from actual issues (Trap 5)."""
    if not issues_data:
        return

    # Sort by severity, deduplicate by category
    severity_order = {"high": 0, "medium": 1, "low": 2}
    sorted_issues = sorted(
        issues_data,
        key=lambda x: severity_order.get(
            str(x.get("severity", "medium")).lower(), 1,
        ),
    )

    seen_cats: set[str] = set()
    top_issues: list[dict[str, Any]] = []
    for iss in sorted_issues:
        cat = str(iss.get("category", "unknown"))
        if cat in seen_cats:
            continue
        seen_cats.add(cat)
        top_issues.append(iss)
        if len(top_issues) >= 5:
            break

    if not top_issues:
        return

    story.append(Paragraph("Top Recommendations", styles["heading"]))
    for i, iss in enumerate(top_issues, 1):
        severity = str(iss.get("severity", "medium")).upper()
        message = str(iss.get("message", ""))
        if len(message) > 120:
            message = message[:117] + "..."
        story.append(Paragraph(
            f"<b>{i}. [{severity}]</b> {message}", styles["body"],
        ))
