# Universal threshold for all content and rule types
minimum_confidence_thresholds:
  # Single universal threshold that works across all content types and rule types
  # This threshold has been optimized based on analysis of the previous complex system
  universal: 0.35  # Balanced threshold for production use
  
  # Legacy compatibility thresholds (mapped to universal threshold)
  # These are maintained only for backward compatibility and all map to the universal threshold
  default: 0.35
  high_confidence: 0.35
  medium_confidence: 0.35
  low_confidence: 0.35
  rejection_threshold: 0.35

# Multi-pass validation configuration (simplified)
# Multi-pass validation is still supported but uses universal threshold
multi_pass_validation:
  # Enable multi-pass validation system
  enabled: true
  
  # Simplified pass configuration - universal threshold applies to all
  passes:
    # Morphological validation pass
    morphological:
      enabled: true
      weight: 0.35
      
    # Contextual validation pass
    contextual:
      enabled: true
      weight: 0.30
      
    # Domain validation pass
    domain:
      enabled: true
      weight: 0.20
      
    # Cross-rule validation pass
    cross_rule:
      enabled: true
      weight: 0.15

# Simplified performance settings
performance_settings:
  # Basic caching configuration
  result_caching:
    enabled: true
    cache_ttl: 600
    max_cache_size: 1000
    
  # Timeout settings
  timeouts:
    individual_pass_timeout: 30
    total_validation_timeout: 120